const rum = [
      {
          "idDrink": "12093",
          "strDrink": "Rum Sour",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Whiskey sour glass",
          "strInstructions": "In a shaker half-filled with ice cubes, combine the rum, lemon juice, and sugar. Shake well. Strain into a sour glass and garnish with the orange slice and the cherry.",
          "strInstructionsES": null,
          "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Rum, Zitronensaft und Zucker vermengen. Gut schütteln. In ein Sourglas abseihen und mit der Orangenscheibe und der Kirsche garnieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum, il succo di limone e lo zucchero. Agitare bene. Filtrare in un bicchiere sour e guarnire con la fetta d'arancia e la ciliegia.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/bylfi21504886323.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "Lemon juice",
          "strIngredient3": "Sugar",
          "strIngredient4": "Orange",
          "strIngredient5": "Maraschino cherry",
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 oz ",
          "strMeasure2": "1 oz ",
          "strMeasure3": "1/2 tsp superfine ",
          "strMeasure4": "1 ",
          "strMeasure5": "1 ",
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-08 16:58:44"
      },
      {
          "idDrink": "12097",
          "strDrink": "Rum Toddy",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "Dissolve powdered sugar in water in an old-fashioned glass. Add rum and one ice cube and stir. Add the twist of lemon peel and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Puderzucker in Wasser in einem old-fashioned Glas auflösen. Rum und einen Eiswürfel dazugeben und umrühren. Die Zitronenschale hinzufügen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Sciogliere lo zucchero in acqua in un bicchiere vecchio stile. Aggiungere il rum e un cubetto di ghiaccio e mescolare. Aggiungere la scorza di limone e servire",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/athdk71504886286.jpg",
          "strIngredient1": "Rum",
          "strIngredient2": "Powdered sugar",
          "strIngredient3": "Lemon peel",
          "strIngredient4": "Water",
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 oz light or dark ",
          "strMeasure2": "2 tsp ",
          "strMeasure3": "1 twist of ",
          "strMeasure4": "2 tsp ",
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-08 16:58:06"
      },
      {
          "idDrink": "14978",
          "strDrink": "Rum Punch",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Punch / Party Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Punch bowl",
          "strInstructions": "Mix all ingredients in a punch bowl and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Alle Zutaten in einer Bowle mischen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Mescolare tutti gli ingredienti in una ciotola da punch e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wyrsxu1441554538.jpg",
          "strIngredient1": "Rum",
          "strIngredient2": "Ginger ale",
          "strIngredient3": "Fruit punch",
          "strIngredient4": "Orange juice",
          "strIngredient5": "Ice",
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "mikey bottle ",
          "strMeasure2": "large bottle ",
          "strMeasure3": "355 ml frozen ",
          "strMeasure4": "355 ml frozen ",
          "strMeasure5": "crushed ",
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2015-09-06 16:48:58"
      },
      {
          "idDrink": "11239",
          "strDrink": "Cherry Rum",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Cocktail glass",
          "strInstructions": "Shake all ingredients with ice, strain into a cocktail glass, and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Alle Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/twsuvr1441554424.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "Cherry brandy",
          "strIngredient3": "Light cream",
          "strIngredient4": null,
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 1/4 oz ",
          "strMeasure2": "1 1/2 tsp ",
          "strMeasure3": "1 tblsp ",
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2015-09-06 16:47:04"
      },
      {
          "idDrink": "12071",
          "strDrink": "Rum Cooler",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Collins glass",
          "strInstructions": "Pour the rum and soda into a collins glass almost filled with ice cubes. Stir well and garnish with the lemon wedge.",
          "strInstructionsES": null,
          "strInstructionsDE": "Den Rum und das Soda in ein Collins-Glas gießen, das fast mit Eiswürfeln gefüllt ist. Gut umrühren und mit dem Zitronenkeil garnieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Versare il rum e la soda in un bicchiere Collins quasi pieno di cubetti di ghiaccio. Mescolate bene e guarnite con lo spicchio di limone",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2hgwsb1504888674.jpg",
          "strIngredient1": "Rum",
          "strIngredient2": "Lemon-lime soda",
          "strIngredient3": "Lemon",
          "strIngredient4": null,
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 oz light or dark ",
          "strMeasure2": "4 oz ",
          "strMeasure3": "1 ",
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-08 17:37:54"
      },
      {
          "idDrink": "16250",
          "strDrink": "Rum Runner",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Punch / Party Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Cocktail glass",
          "strInstructions": "Mix all ingredients in glass & add ice.",
          "strInstructionsES": null,
          "strInstructionsDE": "Alle Zutaten in einem Glas mischen und Eis hinzufügen.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Versare gli ingredienti sul ghiaccio e mescolare.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vqws6t1504888857.jpg",
          "strIngredient1": "Malibu rum",
          "strIngredient2": "Blackberry brandy",
          "strIngredient3": "Orange juice",
          "strIngredient4": "Pineapple juice",
          "strIngredient5": "Cranberry juice",
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 1/2 oz ",
          "strMeasure2": "1 oz ",
          "strMeasure3": "3-4 oz ",
          "strMeasure4": "3-4 oz ",
          "strMeasure5": "3-4 oz ",
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-08 17:40:57"
      },
      {
          "idDrink": "12067",
          "strDrink": "Rum Cobbler",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "In an old-fashioned glass, dissolve the sugar in the club soda. Add crushed ice until the glass is almost full. Add the rum. Stir well. Garnish with the cherry and the orange and lemon slices.",
          "strInstructionsES": null,
          "strInstructionsDE": "In einem old-fashioned Glas den Zucker in der Soda auflösen. Füge zerstoßenes Eis hinzu, bis das Glas fast voll ist. Den Rum hinzufügen. Gut umrühren. Mit der Kirsche und den Orangen- und Zitronenscheiben garnieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "In un bicchiere vecchio stile, sciogli lo zucchero nella soda club. Aggiungere il ghiaccio tritato fino a quando il bicchiere è quasi pieno. Aggiungi il rum. Guarnire con la ciliegia e le fettine di arancia e limone. Mescolare bene. ",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5vh9ld1504390683.jpg",
          "strIngredient1": "Sugar",
          "strIngredient2": "Club soda",
          "strIngredient3": "Lemon",
          "strIngredient4": "Dark rum",
          "strIngredient5": "Maraschino cherry",
          "strIngredient6": "Orange",
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 tsp superfine ",
          "strMeasure2": "3 oz ",
          "strMeasure3": "1 ",
          "strMeasure4": "2 oz ",
          "strMeasure5": "1 ",
          "strMeasure6": "1 ",
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-02 23:18:03"
      },
      {
          "idDrink": "12087",
          "strDrink": "Rum Milk Punch",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Collins glass",
          "strInstructions": "Shake all ingredients (except nutmeg) with ice and strain into a collins glass. Sprinkle nutmeg on top and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Alle Zutaten (außer Muskatnuss) mit Eis schütteln und in ein Collins-Glas abseihen. Muskatnuss darüber streuen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Shakerare tutti gli ingredienti (tranne la noce moscata) con ghiaccio e filtrare in un bicchiere Collins. Cospargere di noce moscata e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/w64lqm1504888810.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "Milk",
          "strIngredient3": "Powdered sugar",
          "strIngredient4": "Nutmeg",
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "2 oz ",
          "strMeasure2": "1 cup ",
          "strMeasure3": "1 tsp ",
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-08 17:40:10"
      },
      {
          "idDrink": "12091",
          "strDrink": "Rum Screwdriver",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Highball glass",
          "strInstructions": "Pour rum into a highball glass over ice cubes. Add orange juice, stir, and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Gießen Sie Rum in ein Highball-Glas über Eiswürfel. Orangensaft hinzufügen, umrühren und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Versare il rum in un bicchiere highball sopra i cubetti di ghiaccio. Aggiungere il succo d'arancia, mescolare e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/4c85zq1511782093.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "Orange juice",
          "strIngredient3": null,
          "strIngredient4": null,
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 1/2 oz ",
          "strMeasure2": "5 oz ",
          "strMeasure3": null,
          "strMeasure4": null,
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-11-27 11:28:14"
      },
      {
          "idDrink": "178309",
          "strDrink": "Espresso Rumtini",
          "strDrinkAlternate": null,
          "strTags": "DinnerParty,StrongFlavor",
          "strVideo": null,
          "strCategory": "Cocktail",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Cocktail glass",
          "strInstructions": "Mix together in a cocktail glass. Garnish with some choclate powder and coffee beans",
          "strInstructionsES": null,
          "strInstructionsDE": null,
          "strInstructionsFR": null,
          "strInstructionsIT": "Mescolare insieme in un bicchiere da cocktail. Guarnire con un po 'di cioccolato in polvere e chicchi di caffè",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/acvf171561574403.jpg",
          "strIngredient1": "Rum",
          "strIngredient2": "Vanilla syrup",
          "strIngredient3": "Espresso",
          "strIngredient4": "Coffee",
          "strIngredient5": null,
          "strIngredient6": null,
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 shot",
          "strMeasure2": "1/2 shot",
          "strMeasure3": "1 shot",
          "strMeasure4": "1 shot",
          "strMeasure5": null,
          "strMeasure6": null,
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "Yes",
          "dateModified": null
      },
      {
          "idDrink": "12089",
          "strDrink": "Rum Old-fashioned",
          "strDrinkAlternate": null,
          "strTags": null,
          "strVideo": null,
          "strCategory": "Ordinary Drink",
          "strIBA": null,
          "strAlcoholic": "Alcoholic",
          "strGlass": "Old-fashioned glass",
          "strInstructions": "Stir powdered sugar, water, and bitters in an old-fashioned glass. When sugar has dissolved add ice cubes and light rum. Add the twist of lime peel, float 151 proof rum on top, and serve.",
          "strInstructionsES": null,
          "strInstructionsDE": "Puderzucker, Wasser und Bitter in einem old-fashioned Glas verrühren. Wenn sich der Zucker aufgelöst hat, Eiswürfel und leichten Rum hinzufügen. Die Limettenspirale hinzufügen, 151er Rum darauf verteilen und servieren.",
          "strInstructionsFR": null,
          "strInstructionsIT": "Mescolare lo zucchero, l'acqua e il bitter in un bicchiere vecchio stile. Quando lo zucchero si sarà sciolto aggiungere i cubetti di ghiaccio e il rum chiaro. Aggiungere la scorza di lime, far galleggiare sopra 151 rum e servire.",
          "strInstructionsZH-HANS": null,
          "strInstructionsZH-HANT": null,
          "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/otn2011504820649.jpg",
          "strIngredient1": "Light rum",
          "strIngredient2": "151 proof rum",
          "strIngredient3": "Powdered sugar",
          "strIngredient4": "Bitters",
          "strIngredient5": "Water",
          "strIngredient6": "Lime peel",
          "strIngredient7": null,
          "strIngredient8": null,
          "strIngredient9": null,
          "strIngredient10": null,
          "strIngredient11": null,
          "strIngredient12": null,
          "strIngredient13": null,
          "strIngredient14": null,
          "strIngredient15": null,
          "strMeasure1": "1 1/2 oz ",
          "strMeasure2": "1 tsp ",
          "strMeasure3": "1/2 tsp ",
          "strMeasure4": "1 dash ",
          "strMeasure5": "1 tsp ",
          "strMeasure6": "Twist of ",
          "strMeasure7": null,
          "strMeasure8": null,
          "strMeasure9": null,
          "strMeasure10": null,
          "strMeasure11": null,
          "strMeasure12": null,
          "strMeasure13": null,
          "strMeasure14": null,
          "strMeasure15": null,
          "strImageSource": null,
          "strImageAttribution": null,
          "strCreativeCommonsConfirmed": "No",
          "dateModified": "2017-09-07 22:44:09"
      }
];

export default rum;